spring:
  profiles:
    active: mysql # 기본 활성 프로필 설정 (여기서 활성 프로필 변경하며 실행)

# 1) H2 프로필
---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:study_batch;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa    # 기본 유저
      password:       # 기본 비밀번호 (없음)
      driver-class-name: org.h2.Driver

  batch:
    jdbc:
      initialize-schema: embedded

# 2) MYSQL 프로필
---
spring:
  config:
    activate:
      on-profile: mysql

  datasource:
    url: jdbc:mysql://localhost:3307/study_batch?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  batch:
    jdbc:
      initialize-schema: never
    job:
      name: StudyJob # 새로운 Job 이 추가되고 실행해야 할 때 해당 내용 변경

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true